# Generated by Django 5.0.3 on 2024-04-09 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_main_branch', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'branchs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rnc', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('date_founded', models.DateField(auto_now=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('logo_src', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'suscribers',
            },
        ),
        migrations.CreateModel(
            name='BranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.address')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.branch')),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.phone')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.company'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.branch')),
            ],
            options={
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='SuscriberCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.company')),
                ('suscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.suscriber')),
            ],
        ),
    ]
