# Generated by Django 5.0.3 on 2024-04-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmanagement', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businessmanagement.department')),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.userprofile')),
            ],
            options={
                'verbose_name_plural': 'usersdepartments',
            },
        ),
    ]
