# Generated by Django 5.0.3 on 2024-04-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmanagement', '0002_userdepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suscriber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userdepartment',
            options={},
        ),
        migrations.RemoveField(
            model_name='suscribercompany',
            name='suscriber_id',
        ),
        migrations.AddField(
            model_name='suscribercompany',
            name='suscriber',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='businessmanagement.suscriber'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branchs',
        ),
        migrations.AlterModelTable(
            name='branchaddress',
            table='branchs_addresses',
        ),
        migrations.AlterModelTable(
            name='branchphone',
            table='branchs_phones',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='suscriber',
            table='suscribers',
        ),
        migrations.AlterModelTable(
            name='userdepartment',
            table='users_departments',
        ),
    ]
