# Generated by Django 5.0.3 on 2024-04-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmanagement', '0003_alter_branch_options_alter_company_options_and_more'),
        ('usermanagement', '0003_alter_userprofile_person_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.person')),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businessmanagement.portfolio')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=100)),
                ('bonus_type', models.CharField(max_length=100)),
                ('bonus', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.person')),
            ],
            options={
                'db_table': 'promoters',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_level', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='seller_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='businessmanagement.seller'),
        ),
    ]
