# Generated by Django 5.0.3 on 2024-04-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_address_options_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.person'),
        ),
    ]
